version: '2'

services:
  web:
    build: ./docker/web
    container_name: app
    volumes:
     - "./mt:/var/www/html"
     - "./cgi-bin:/var/www/cgi-bin"
     - "./mt-config.cgi:/var/www/cgi-bin/mt/mt-config.cgi"
     - "./docker/web/httpd.conf:/etc/httpd/conf/httpd.conf"
    ports:
      - "8010:80"
    links:
     - "db:db"

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: #作成するDB名
      MYSQL_ROOT_PASSWORD: root